Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Ricarda>cd C:\Users\Ricarda\tensorflow-for-poets-2\tf_files

C:\Users\Ricarda\tensorflow-for-poets-2\tf_files>IMAGE_SIZE=224ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}"python -m scripts.retrain \  --bottleneck_dir=tf_files/bottlenecks \  --model_dir=tf_files/models/"${ARCHITECTURE}" \  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" \  --output_graph=tf_files/retrained_graph.pb \  --output_labels=tf_files/retrained_labels.txt \  --architecture="${ARCHITECTURE}" \  --image_dir=tf_files/C:\Users\Ricarda\tensorflow-for-poets-2\tf_files\animal_photos
Der Befehl "IMAGE_SIZE" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Ricarda\tensorflow-for-poets-2\tf_files>IMAGE_SIZE=224ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}"python -m scripts.retrain
Der Befehl "IMAGE_SIZE" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Ricarda\tensorflow-for-poets-2\tf_files>cd..

C:\Users\Ricarda\tensorflow-for-poets-2>cd..

C:\Users\Ricarda>cd tensorflow-for-poets-2

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.retrain \  --bottleneck_dir=tf_files/bottlenecks \  --model_dir=tf_files/models/"${ARCHITECTURE}" \  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" \  --output_graph=tf_files/retrained_graph.pb \  --output_labels=tf_files/retrained_labels.txt \  --architecture="${ARCHITECTURE}" \  --image_dir=tf_files/animal_photos
ERROR:tensorflow:Couldn't understand architecture name '${architecture}'
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 976, in main
    model_info = create_model_info(FLAGS.architecture)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 923, in create_model_info
    raise ValueError('Unknown architecture', architecture)
ValueError: ('Unknown architecture', '${architecture}')

C:\Users\Ricarda\tensorflow-for-poets-2>SET IMAGE_SIZE=224

C:\Users\Ricarda\tensorflow-for-poets-2>SET ARCHITECTURE="mobilenet_0.50_%IMAGE_SIZE%"

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.retrain \  --bottleneck_dir=tf_files/bottlenecks \  --model_dir=tf_files/models/"${ARCHITECTURE}" \  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" \  --output_graph=tf_files/retrained_graph.pb \  --output_labels=tf_files/retrained_labels.txt \  --architecture="${ARCHITECTURE}" \  --image_dir=tf_files/animal_photos
ERROR:tensorflow:Couldn't understand architecture name '${architecture}'
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 976, in main
    model_info = create_model_info(FLAGS.architecture)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 923, in create_model_info
    raise ValueError('Unknown architecture', architecture)
ValueError: ('Unknown architecture', '${architecture}')

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.retrain \  --bottleneck_dir=tf_files/bottlenecks \  --model_dir=tf_files/models/"${ARCHITECTURE}" \  --summaries_dir=tf_files/training_summaries/"%ARCHITECTURE%" \  --output_graph=tf_files/retrained_graph.pb \  --output_labels=tf_files/retrained_labels.txt \  --architecture="%ARCHITECTURE%" \  --image_dir=tf_files/animal_photos
>> Downloading mobilenet_v1_0.50_224_frozen.tgz 100.1%
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 982, in main
    maybe_download_and_extract(model_info['data_url'])
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 339, in maybe_download_and_extract
    'bytes.')
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\tf_logging.py", line 116, in info
    _get_logger().info(msg, *args, **kwargs)
Message: 'Successfully downloaded'
Arguments: ('mobilenet_v1_0.50_224_frozen.tgz', 6308169, 'bytes.')
INFO:tensorflow:Looking for images in 'elephant'
INFO:tensorflow:Looking for images in 'giraffes'
INFO:tensorflow:Looking for images in 'zebra'
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\elephant-A10-2,8,1-500.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\elephant-A12-3G-45.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\elephant-A34-7K-226.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\elephant-A34-9M-232.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\elephant_A10-2,8,1-499.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\Inkedelephant-A12-3G-45_LI.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\Inkedelephant-A34-7K-226_LI.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\Inkedelephant-A34-9M-232_LI.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\Inkedelephant_A10-2,8,1-499_LI.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\elephant\Inkedelephant-A10-2,8,1-500_LI.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe-A3-5-F-115.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe-A3-5-F-116.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe-A3-6-J,K-177.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A10-2-8,1-482.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A17-2B-32-roh.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A29-4-D-78.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A32-2-C-22.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A34-3-B-69.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A34-8-H-189J.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A37-1-A-1.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A38-3,4-F-382.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A46-1-A-2.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A47-1-B-102.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A47-1-B-103.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A47-1-B-104.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A47-1-B-105.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A51-3-H-116.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A56-3-H-122.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A56-3-I-126.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A57-1-B-109.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A57-1-B-82.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A57-2-C-129.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A57-2-C-200.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A57-2-C-205.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A6-4-H-60.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A6-4-H-61.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A6-4-H-62.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A6-4-H-63.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A60-1-A-1.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A60-2-A-19.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A63-1-A-1.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A63-1X-C-4.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A51-3-H-117.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A6-7-L-607.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A51-3-H-115.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\giraffes\giraffe_A7-1X-A-1.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A10-2-498.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A10-2-661.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A10-2-663.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A47-1A-30.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A47-1A-31.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A47-1A-32.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A49-1A-1.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A56-1C-73.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:100 bottleneck files created.
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A56-2G-110.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A56-2G-111.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A6-2XC-30.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A10-2-662.jpg_mobilenet_0.50_224.txt
INFO:tensorflow:Creating bottleneck at tf_files/bottlenecks\zebra\zebra-A6-7L-594.jpg_mobilenet_0.50_224.txt
WARNING:tensorflow:From C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py:790: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:2018-05-15 16:25:55.059092: Step 0: Train accuracy = 81.0%
INFO:tensorflow:2018-05-15 16:25:55.105966: Step 0: Cross entropy = 0.483715
CRITICAL:tensorflow:Label zebra has no images in the category validation.
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1090, in main
    FLAGS.architecture))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 525, in get_random_cached_bottlenecks
    image_dir, category)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 234, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zero



C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image \    --graph=tf_files/retrained_graph.pb  \    --image=C:\Users\Ricarda\Pictures\Sonstiges\image.jpg
usage: label_image.py [-h] [--image IMAGE] [--graph GRAPH] [--labels LABELS]
                      [--input_height INPUT_HEIGHT]
                      [--input_width INPUT_WIDTH] [--input_mean INPUT_MEAN]
                      [--input_std INPUT_STD] [--input_layer INPUT_LAYER]
                      [--output_layer OUTPUT_LAYER]
label_image.py: error: unrecognized arguments: \ \

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image \    --graph=tf_files/retrained_graph.pb  \    --image=/image.jpg
usage: label_image.py [-h] [--image IMAGE] [--graph GRAPH] [--labels LABELS]
                      [--input_height INPUT_HEIGHT]
                      [--input_width INPUT_WIDTH] [--input_mean INPUT_MEAN]
                      [--input_std INPUT_STD] [--input_layer INPUT_LAYER]
                      [--output_layer OUTPUT_LAYER]
label_image.py: error: unrecognized arguments: \ \

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 112, in <module>
    graph = load_graph(model_file)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 31, in load_graph
    with open(model_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tf_files/retrained_graph.pb'

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 112, in <module>
    graph = load_graph(model_file)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 31, in load_graph
    with open(model_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tf_files/retrained_graph.pb'

C:\Users\Ricarda\tensorflow-for-poets-2>--graph=tf_files/retrained_graph.pb
Der Befehl "--graph" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.retrain \  --bottleneck_dir=tf_files/bottlenecks \  --model_dir=tf_files/models/"${ARCHITECTURE}" \  --summaries_dir=tf_files/training_summaries/"%ARCHITECTURE%" \  --output_graph=tf_files/retrained_graph.pb \  --output_labels=tf_files/retrained_labels.txt \  --architecture="%ARCHITECTURE%" \  --image_dir=tf_files/animal_photos
INFO:tensorflow:Looking for images in 'elephant'
INFO:tensorflow:Looking for images in 'giraffes'
INFO:tensorflow:Looking for images in 'zebra'
INFO:tensorflow:100 bottleneck files created.
WARNING:tensorflow:From C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py:790: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:2018-05-15 16:48:10.122102: Step 0: Train accuracy = 75.0%
INFO:tensorflow:2018-05-15 16:48:10.200253: Step 0: Cross entropy = 0.620683
CRITICAL:tensorflow:Label zebra has no images in the category validation.
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 1090, in main
    FLAGS.architecture))
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 525, in get_random_cached_bottlenecks
    image_dir, category)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\retrain.py", line 234, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zero

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image \    --graph=tf_files/retrained_graph.pb  \    --image=YOUR_PATH_TO_IMAGE_HERE
usage: label_image.py [-h] [--image IMAGE] [--graph GRAPH] [--labels LABELS]
                      [--input_height INPUT_HEIGHT]
                      [--input_width INPUT_WIDTH] [--input_mean INPUT_MEAN]
                      [--input_std INPUT_STD] [--input_layer INPUT_LAYER]
                      [--output_layer OUTPUT_LAYER]
label_image.py: error: unrecognized arguments: \ \

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image \    --graph=tf_files/retrained_graph.pb  \    --image=\image.jpg
usage: label_image.py [-h] [--image IMAGE] [--graph GRAPH] [--labels LABELS]
                      [--input_height INPUT_HEIGHT]
                      [--input_width INPUT_WIDTH] [--input_mean INPUT_MEAN]
                      [--input_std INPUT_STD] [--input_layer INPUT_LAYER]
                      [--output_layer OUTPUT_LAYER]
label_image.py: error: unrecognized arguments: \ \

C:\Users\Ricarda\tensorflow-for-poets-2>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> -m scripts.label_image
  File "<stdin>", line 1
    -m scripts.label_image
             ^
SyntaxError: invalid syntax
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()

C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image ^   --graph=tf_files/retrained_graph.pb  ^   --image=/image.jpg
2018-05-15 16:56:30.603390: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1273] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: NewRandomAccessFile failed to Create/Open: /image.jpg : Das System kann die angegebene Datei nicht finden.
; No such file or directory
2018-05-15 16:56:30.760103: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1273] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: NewRandomAccessFile failed to Create/Open: /image.jpg : Das System kann die angegebene Datei nicht finden.
; No such file or directory
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: /image.jpg : Das System kann die angegebene Datei nicht finden.
; No such file or directory
         [[Node: file_reader = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](file_reader/filename)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 117, in <module>
    input_std=input_std)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 59, in read_tensor_from_image_file
    result = sess.run(normalized)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: /image.jpg : Das System kann die angegebene Datei nicht finden.
; No such file or directory
         [[Node: file_reader = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](file_reader/filename)]]

Caused by op 'file_reader', defined at:
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 117, in <module>
    input_std=input_std)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 42, in read_tensor_from_image_file
    file_reader = tf.read_file(file_name, input_name)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 551, in read_file
    "ReadFile", filename=filename, name=name)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): NewRandomAccessFile failed to Create/Open: /image.jpg : Das System kann die angegebene Datei nicht finden.
; No such file or directory
         [[Node: file_reader = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](file_reader/filename)]]


C:\Users\Ricarda\tensorflow-for-poets-2>python -m scripts.label_image ^   --graph=tf_files/retrained_graph.pb  ^   --image=C:\Users\Ricarda\tensorflow-for-poets-2\image.jpg
Traceback (most recent call last):
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ricarda\tensorflow-for-poets-2\scripts\label_image.py", line 121, in <module>
    input_operation = graph.get_operation_by_name(input_name);
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3606, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\Ricarda\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3538, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'import/input' refers to an Operation not in the graph."

C:\Users\Ricarda\tensorflow-for-poets-2>